### ISSUE TITLE
Doesn't seem to work in Pop!_OS

### ISSUE THREAD

**Issue by senntore** [EyeOdin/project_pages#1]
OS: Pop!_OS 22.04
Krita: 5.1.5
The Plugin Manager is showing this error when I hover over Project Pages:
![image](https://user-images.githubusercontent.com/58325574/218051762-7ec5d07a-a4c1-4320-828d-2cd57cc2f6da.png)

Sorry if it's too early to report issues on this plugin.

**Comment by EyeOdin** [comment]
I updated it, should be good now. That was a left over from an experiment I did when creating it.
